name: Xcode - Build and Analyze

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Install pods
        run: cd ios && pod install && cd ..
      - name: Execute Fastlane version
        run: cd ios && fastlane increment_version && cd ..
      - name: Execute Fastlane commandss
        run: cd ios && fastlane beta
  # release-android:
  #   name: Build and release Android app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.x"
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: "2.x"
  #     - name: Install Fastlane
  #       run: cd android && bundle install && cd ..
  #     - name: Install packages
  #       run: yarn install
  #     - name: Prebuild
  #       run: cd android && fastlane beta_build && cd ..
  #     - name: Execute Fastlane command
  #       run: cd android && fastlane firebase_beta
